    @hostname = http://localhost:3002


// create a new hotel
###
post {{hostname}}/users
Content-Type: application/json

{
    "firstName": "Nurse",
  "lastName": "Agbey",
  "email": "benjamin100ist@gmail.com",
  "password": "123456",
  "role": "super-admin",
  "hotelId": "6427564c83875d3af28ec71c"
}

###

// get all userss
get {{hostname}}/users
###

### 
//update a users with id
put {{hostname}}/users/6426c4a82c732ee350c9171e
Content-Type: application/json

{
    "usersNumber":"2"
}

### 
// delete a users
delete {{hostname}}/users/6426c4a12c732ee350c9171c

### 
// link if a user forgets password
post {{hostname}}/users/forgot-password
Content-Type: application/json

{
    "email":"benjamin100ist@hotmail.com"
}

### 
// link to reset user's password
post {{hostname}}/users/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlbmphbWlubW9yZGVkemlAaG90bWFpbC5jb20iLCJpYXQiOjE2ODAzMDgyNjgsImV4cCI6MTY4MDMxMTg2OH0.h-1ZvwYdgBo9hRUImlHbOPJRjeXWz0_53A5cf9f-bT8
Content-Type: application/json

{
    "password":"1234567"
}

###
// login user
post {{hostname}}/users/login
Content-Type: application/json

{
    "email":"benjamin100ist@gmail.com",
    "password":"123456"
}

### logout

post {{hostname}}/users/logout
Content-Type: application/json

